// Windissect recovered ABI metadata — DO NOT EDIT.
// Portable across C++17, C++20, C++23, and C++26 draft modes.
#pragma once
#include <cstddef>
#include <cstdint>

namespace windissect_abi {
struct TypeLayout { const char* name; std::uint64_t size; const char* kind; };
struct FieldLayout { const char* owner; const char* name; std::uint32_t type_index; std::uint64_t offset; bool is_static; };
struct FieldObservation { const char* owner; const char* suggested_name; std::uint64_t offset; std::uint32_t width; const char* access; std::uint32_t evidence_rva; const char* evidence_symbol; const char* confidence; };
struct BaseLayout { const char* derived; const char* base; std::int64_t offset; bool is_virtual; const char* evidence; const char* confidence; };
struct VTableLayout { const char* name; std::uint32_t rva; std::uint32_t slots; const char* evidence; const char* confidence; };
struct VTableSlotLayout { std::uint32_t table_rva; std::uint32_t slot; std::uint32_t target_rva; const char* target_id; const char* target_name; bool ambiguous; std::int32_t this_adjustment; };

inline constexpr TypeLayout types[] = {
    {"CAutoPickedDevice", 0ULL, "layout-evidence"},
    {"CCancelConnection2", 0ULL, "layout-evidence"},
    {"CCountingResource", 0ULL, "layout-evidence"},
    {"CGetConnection", 0ULL, "layout-evidence"},
    {"CGetConnection3", 0ULL, "layout-evidence"},
    {"CGetConnectionPerformance", 0ULL, "layout-evidence"},
    {"CGetResourceInformation", 0ULL, "layout-evidence"},
    {"CGetResourceParent", 0ULL, "layout-evidence"},
    {"CMprOperation", 0ULL, "layout-evidence"},
    {"CProviderOpenEnum", 0ULL, "layout-evidence"},
    {"CRoutedOperation", 0ULL, "layout-evidence"},
    {"CRoutedOperation::CPathCache", 0ULL, "layout-evidence"},
    {"CUseConnection", 0ULL, "layout-evidence"},
    {"wil", 0ULL, "layout-evidence"},
    {"wil::details::out_param_t<class wistd::unique_ptr<class wistd::unique_ptr<unsigned char[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> >[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> > >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct HKEY__*, long (__cdecl *)(struct HKEY__*), long (__cdecl RegCloseKey::*)(struct HKEY__*), struct wistd::integral_constant<uint64_t, 0>, struct HKEY__*, struct HKEY__*, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void (__cdecl *)(void *), void (__cdecl SspiLocalFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<void *, void (__cdecl *)(void *), void (__cdecl SspiFreeAuthIdentity::*)(void *), struct wistd::integral_constant<uint64_t, 0>, void *, void *, 0, std::nullptr_t> >", 0ULL, "layout-evidence"},
    {"wil::last_error_context", 0ULL, "layout-evidence"},
    {"wil::unique_any_t<class wil::details::unique_storage<struct wil::details::resource_policy<unsigned char *, void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(unsigned char *), struct wistd::integral_constant<uint64_t, 0>, unsigned char *, unsigned char *, 0, std::nullptr_t> > >", 0ULL, "layout-evidence"},
    {nullptr, 0, nullptr},
};
inline constexpr std::size_t type_count = (sizeof(types) / sizeof(types[0])) - 1;
inline constexpr FieldLayout fields[] = {
    {nullptr, nullptr, 0, 0, false},
};
inline constexpr std::size_t field_count = (sizeof(fields) / sizeof(fields[0])) - 1;
inline constexpr FieldObservation field_observations[] = {
    {"CAutoPickedDevice", nullptr, 0ULL, 8U, "write", 0xD6ACU, "?Init@CAutoPickedDevice@@QEAAKPEAGPEAKPEBG2KK@Z", "likely"},
    {"CAutoPickedDevice", nullptr, 0ULL, 4U, "write", 0xD6ACU, "?Init@CAutoPickedDevice@@QEAAKPEAGPEAKPEBG2KK@Z", "likely"},
    {"CAutoPickedDevice", nullptr, 0ULL, 4U, "read", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 0ULL, 4U, "write", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 4ULL, 4U, "write", 0xD6ACU, "?Init@CAutoPickedDevice@@QEAAKPEAGPEAKPEBG2KK@Z", "likely"},
    {"CAutoPickedDevice", nullptr, 4ULL, 4U, "read", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 4ULL, 4U, "write", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 8ULL, 4U, "write", 0xD6ACU, "?Init@CAutoPickedDevice@@QEAAKPEAGPEAKPEBG2KK@Z", "likely"},
    {"CAutoPickedDevice", nullptr, 8ULL, 4U, "read", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 12ULL, 4U, "write", 0xD6ACU, "?Init@CAutoPickedDevice@@QEAAKPEAGPEAKPEBG2KK@Z", "likely"},
    {"CAutoPickedDevice", nullptr, 12ULL, 4U, "read", 0xD6ACU, "?Init@CAutoPickedDevice@@QEAAKPEAGPEAKPEBG2KK@Z", "likely"},
    {"CAutoPickedDevice", nullptr, 12ULL, 4U, "read", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 16ULL, 4U, "write", 0xD6ACU, "?Init@CAutoPickedDevice@@QEAAKPEAGPEAKPEBG2KK@Z", "likely"},
    {"CAutoPickedDevice", nullptr, 16ULL, 4U, "write", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 20ULL, 2U, "write", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CAutoPickedDevice", nullptr, 22ULL, 4U, "write", 0xECF0U, "?PickDevice@CAutoPickedDevice@@QEAAKXZ", "likely"},
    {"CCancelConnection2", nullptr, 40ULL, 8U, "read", 0x9CC0U, "?GetResult@CCancelConnection2@@MEAAKXZ", "likely"},
    {"CCancelConnection2", nullptr, 56ULL, 8U, "read", 0x9CC0U, "?GetResult@CCancelConnection2@@MEAAKXZ", "likely"},
    {"CCancelConnection2", nullptr, 56ULL, 8U, "read", 0xBE00U, "?ValidateRoutedParameters@CCancelConnection2@@MEAAKPEAPEBG00@Z", "likely"},
    {"CCancelConnection2", nullptr, 56ULL, 8U, "read", 0xD630U, "?TestProvider@CCancelConnection2@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CCancelConnection2", nullptr, 64ULL, 4U, "read", 0x9CC0U, "?GetResult@CCancelConnection2@@MEAAKXZ", "likely"},
    {"CCancelConnection2", nullptr, 64ULL, 4U, "read", 0xBE00U, "?ValidateRoutedParameters@CCancelConnection2@@MEAAKPEAPEBG00@Z", "likely"},
    {"CCancelConnection2", nullptr, 64ULL, 4U, "read", 0xD630U, "?TestProvider@CCancelConnection2@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CCancelConnection2", nullptr, 68ULL, 4U, "read", 0x9CC0U, "?GetResult@CCancelConnection2@@MEAAKXZ", "likely"},
    {"CCancelConnection2", nullptr, 68ULL, 4U, "read", 0xD630U, "?TestProvider@CCancelConnection2@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnection", nullptr, 56ULL, 8U, "read", 0xB130U, "?ValidateRoutedParameters@CGetConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnection", nullptr, 56ULL, 8U, "read", 0xDCC0U, "?TestProvider@CGetConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnection", nullptr, 64ULL, 8U, "read", 0xDCC0U, "?TestProvider@CGetConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnection", nullptr, 72ULL, 8U, "read", 0xDCC0U, "?TestProvider@CGetConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnection", nullptr, 80ULL, 8U, "read", 0xB130U, "?ValidateRoutedParameters@CGetConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnection3", nullptr, 56ULL, 8U, "read", 0xB190U, "?ValidateRoutedParameters@CGetConnection3@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnection3", nullptr, 56ULL, 8U, "read", 0xBA50U, "?TestProvider@CGetConnection3@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnection3", nullptr, 64ULL, 8U, "read", 0xB190U, "?ValidateRoutedParameters@CGetConnection3@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnection3", nullptr, 72ULL, 4U, "read", 0xB190U, "?ValidateRoutedParameters@CGetConnection3@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnection3", nullptr, 72ULL, 4U, "read", 0xBA50U, "?TestProvider@CGetConnection3@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnection3", nullptr, 80ULL, 8U, "read", 0xB190U, "?ValidateRoutedParameters@CGetConnection3@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnection3", nullptr, 80ULL, 8U, "read", 0xBA50U, "?TestProvider@CGetConnection3@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnection3", nullptr, 88ULL, 8U, "read", 0xB190U, "?ValidateRoutedParameters@CGetConnection3@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnection3", nullptr, 88ULL, 8U, "read", 0xBA50U, "?TestProvider@CGetConnection3@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnectionPerformance", nullptr, 56ULL, 8U, "read", 0xD450U, "?ValidateRoutedParameters@CGetConnectionPerformance@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnectionPerformance", nullptr, 64ULL, 8U, "read", 0xD450U, "?ValidateRoutedParameters@CGetConnectionPerformance@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnectionPerformance", nullptr, 64ULL, 8U, "read", 0xDD30U, "?TestProvider@CGetConnectionPerformance@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetConnectionPerformance", nullptr, 72ULL, 8U, "write", 0xD450U, "?ValidateRoutedParameters@CGetConnectionPerformance@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnectionPerformance", nullptr, 72ULL, 8U, "read", 0xD450U, "?ValidateRoutedParameters@CGetConnectionPerformance@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetConnectionPerformance", nullptr, 72ULL, 8U, "read", 0xDD30U, "?TestProvider@CGetConnectionPerformance@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetResourceInformation", nullptr, 56ULL, 8U, "read", 0xBDD0U, "?TestProvider@CGetResourceInformation@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetResourceInformation", nullptr, 56ULL, 8U, "read", 0xBF90U, "?ValidateRoutedParameters@CGetResourceInformation@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetResourceInformation", nullptr, 64ULL, 8U, "read", 0xBDD0U, "?TestProvider@CGetResourceInformation@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetResourceInformation", nullptr, 64ULL, 8U, "read", 0xBF90U, "?ValidateRoutedParameters@CGetResourceInformation@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetResourceInformation", nullptr, 72ULL, 8U, "read", 0xBDD0U, "?TestProvider@CGetResourceInformation@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetResourceInformation", nullptr, 72ULL, 8U, "read", 0xBF90U, "?ValidateRoutedParameters@CGetResourceInformation@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetResourceInformation", nullptr, 80ULL, 8U, "read", 0xBDD0U, "?TestProvider@CGetResourceInformation@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetResourceInformation", nullptr, 80ULL, 8U, "read", 0xBF90U, "?ValidateRoutedParameters@CGetResourceInformation@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetResourceParent", nullptr, 56ULL, 8U, "read", 0xD760U, "?ValidateRoutedParameters@CGetResourceParent@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetResourceParent", nullptr, 56ULL, 8U, "read", 0x12C30U, "?TestProvider@CGetResourceParent@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetResourceParent", nullptr, 64ULL, 8U, "read", 0xD760U, "?ValidateRoutedParameters@CGetResourceParent@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetResourceParent", nullptr, 64ULL, 8U, "read", 0x12C30U, "?TestProvider@CGetResourceParent@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CGetResourceParent", nullptr, 72ULL, 8U, "read", 0xD760U, "?ValidateRoutedParameters@CGetResourceParent@@MEAAKPEAPEBG00@Z", "likely"},
    {"CGetResourceParent", nullptr, 72ULL, 8U, "read", 0x12C30U, "?TestProvider@CGetResourceParent@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CMprOperation", nullptr, 0ULL, 8U, "read", 0x6300U, "?Perform@CMprOperation@@UEAAKXZ", "likely"},
    {"CProviderOpenEnum", nullptr, 40ULL, 8U, "read", 0xA0D0U, "?GetResult@CProviderOpenEnum@@MEAAKXZ", "likely"},
    {"CProviderOpenEnum", nullptr, 56ULL, 4U, "read", 0xD5C0U, "?TestProvider@CProviderOpenEnum@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CProviderOpenEnum", nullptr, 60ULL, 4U, "read", 0xD5C0U, "?TestProvider@CProviderOpenEnum@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CProviderOpenEnum", nullptr, 64ULL, 4U, "read", 0xD5C0U, "?TestProvider@CProviderOpenEnum@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CProviderOpenEnum", nullptr, 72ULL, 8U, "read", 0xD5C0U, "?TestProvider@CProviderOpenEnum@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CProviderOpenEnum", nullptr, 72ULL, 8U, "read", 0xD670U, "?ValidateRoutedParameters@CProviderOpenEnum@@MEAAKPEAPEBG00@Z", "likely"},
    {"CProviderOpenEnum", nullptr, 72ULL, 8U, "write", 0xD670U, "?ValidateRoutedParameters@CProviderOpenEnum@@MEAAKPEAPEBG00@Z", "likely"},
    {"CProviderOpenEnum", nullptr, 80ULL, 8U, "read", 0xA0D0U, "?GetResult@CProviderOpenEnum@@MEAAKXZ", "likely"},
    {"CProviderOpenEnum", nullptr, 88ULL, 8U, "read", 0xA0D0U, "?GetResult@CProviderOpenEnum@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 0ULL, 8U, "read", 0x82F0U, "?ValidateParameters@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 0ULL, 8U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 8ULL, 4U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 12ULL, 4U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 16ULL, 8U, "write", 0x82F0U, "?ValidateParameters@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 16ULL, 8U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 24ULL, 2U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 26ULL, 2U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 40ULL, 8U, "write", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 48ULL, 4U, "write", 0x82F0U, "?ValidateParameters@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 48ULL, 4U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 52ULL, 4U, "write", 0x82F0U, "?ValidateParameters@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CRoutedOperation", nullptr, 52ULL, 4U, "read", 0xA1D0U, "?GetResult@CRoutedOperation@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 0ULL, 8U, "write", 0x8294U, "??1CUseConnection@@QEAA@XZ", "likely"},
    {"CUseConnection", nullptr, 0ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 8ULL, 4U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 12ULL, 4U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 16ULL, 8U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 40ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 40ULL, 8U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 48ULL, 4U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 52ULL, 4U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 56ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 56ULL, 8U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 56ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 64ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 64ULL, 8U, "read", 0xD890U, "?ValidateRoutedParameters@CUseConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CUseConnection", nullptr, 64ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 72ULL, 8U, "read", 0x8294U, "??1CUseConnection@@QEAA@XZ", "likely"},
    {"CUseConnection", nullptr, 72ULL, 8U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 72ULL, 8U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 72ULL, 8U, "read", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 72ULL, 8U, "write", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 72ULL, 8U, "read", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "read", 0x8294U, "??1CUseConnection@@QEAA@XZ", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "write", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "read", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 80ULL, 8U, "write", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 88ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 88ULL, 1U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 88ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 88ULL, 1U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 88ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 88ULL, 4U, "read", 0xD890U, "?ValidateRoutedParameters@CUseConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CUseConnection", nullptr, 88ULL, 4U, "write", 0xD890U, "?ValidateRoutedParameters@CUseConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CUseConnection", nullptr, 88ULL, 4U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 96ULL, 8U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 96ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 104ULL, 4U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 104ULL, 4U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 112ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 112ULL, 8U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 112ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 120ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 120ULL, 4U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 120ULL, 4U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 128ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 128ULL, 8U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 128ULL, 8U, "read", 0xD890U, "?ValidateRoutedParameters@CUseConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CUseConnection", nullptr, 128ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 136ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 136ULL, 8U, "read", 0xD890U, "?ValidateRoutedParameters@CUseConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CUseConnection", nullptr, 136ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 144ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 144ULL, 8U, "read", 0xD890U, "?ValidateRoutedParameters@CUseConnection@@MEAAKPEAPEBG00@Z", "likely"},
    {"CUseConnection", nullptr, 144ULL, 8U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 152ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 152ULL, 4U, "write", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 152ULL, 4U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 152ULL, 4U, "write", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 156ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 156ULL, 4U, "write", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 156ULL, 4U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 176ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 200ULL, 16U, "write", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 204ULL, 4U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 216ULL, 16U, "write", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 216ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 216ULL, 8U, "write", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 216ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 216ULL, 8U, "write", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 216ULL, 8U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 216ULL, 8U, "write", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 224ULL, 8U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 224ULL, 8U, "read", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 232ULL, 16U, "write", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 248ULL, 4U, "write", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 248ULL, 4U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 248ULL, 4U, "read", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 248ULL, 4U, "write", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 252ULL, 1U, "read", 0xBBC0U, "?TestProviderWorker@CUseConnection@@AEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 252ULL, 1U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 253ULL, 1U, "read", 0x8294U, "??1CUseConnection@@QEAA@XZ", "likely"},
    {"CUseConnection", nullptr, 253ULL, 1U, "read", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 253ULL, 1U, "write", 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "likely"},
    {"CUseConnection", nullptr, 253ULL, 2U, "read-write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 253ULL, 2U, "write", 0xE53CU, "??0CUseConnection@@QEAA@PEAUHWND__@@PEAU_NETRESOURCEW@@PEAXKKPEAEKPEAGPEAK5@Z", "likely"},
    {"CUseConnection", nullptr, 253ULL, 1U, "read", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 253ULL, 1U, "write", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 254ULL, 1U, "read", 0x8294U, "??1CUseConnection@@QEAA@XZ", "likely"},
    {"CUseConnection", nullptr, 254ULL, 1U, "read", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"CUseConnection", nullptr, 254ULL, 1U, "write", 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "likely"},
    {"wil", nullptr, 0ULL, 8U, "write", 0xE514U, "??$out_param@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@wil@@YA?AU?$out_param_t@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@details@0@AEAV?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@Z", "likely"},
    {"wil", nullptr, 8ULL, 8U, "read-write", 0xE514U, "??$out_param@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@wil@@YA?AU?$out_param_t@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@details@0@AEAV?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@Z", "likely"},
    {"wil", nullptr, 16ULL, 1U, "write", 0xE514U, "??$out_param@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@wil@@YA?AU?$out_param_t@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@details@0@AEAV?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@Z", "likely"},
    {"wil::details::out_param_t<class wistd::unique_ptr<class wistd::unique_ptr<unsigned char[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> >[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> > >", nullptr, 0ULL, 8U, "read", 0xE644U, "??1?$out_param_t@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::out_param_t<class wistd::unique_ptr<class wistd::unique_ptr<unsigned char[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> >[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> > >", nullptr, 8ULL, 8U, "read", 0xE644U, "??1?$out_param_t@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::out_param_t<class wistd::unique_ptr<class wistd::unique_ptr<unsigned char[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> >[0], struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> > >", nullptr, 16ULL, 1U, "read", 0xE644U, "??1?$out_param_t@V?$unique_ptr@$$BY0A@V?$unique_ptr@$$BY0A@EU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@U?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<struct HKEY__*, long (__cdecl *)(struct HKEY__*), long (__cdecl RegCloseKey::*)(struct HKEY__*), struct wistd::integral_constant<uint64_t, 0>, struct HKEY__*, struct HKEY__*, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0xDF9CU, "??1?$unique_storage@U?$resource_policy@PEAUHKEY__@@P6AJPEAU1@@Z$1?RegCloseKey@@YAJ0@ZU?$integral_constant@_K$0A@@wistd@@PEAU1@PEAU1@$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void (__cdecl *)(void *), void (__cdecl SspiLocalFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0xE67CU, "??1?$unique_storage@U?$resource_policy@PEAGP6AXPEAX@Z$1?SspiLocalFree@@YAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAGPEAG$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<unsigned short *, void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(unsigned short *), struct wistd::integral_constant<uint64_t, 0>, unsigned short *, unsigned short *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0xDF68U, "??1?$unique_storage@U?$resource_policy@PEAGP6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAGPEAG$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::details::unique_storage<struct wil::details::resource_policy<void *, void (__cdecl *)(void *), void (__cdecl SspiFreeAuthIdentity::*)(void *), struct wistd::integral_constant<uint64_t, 0>, void *, void *, 0, std::nullptr_t> >", nullptr, 0ULL, 8U, "read", 0xDFC0U, "??1?$unique_storage@U?$resource_policy@PEAXP6AXPEAX@Z$1?SspiFreeAuthIdentity@@YAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAXPEAX$0A@$$T@details@wil@@@details@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 0ULL, 1U, "write", 0xE618U, "??0last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 0ULL, 1U, "read", 0xE6C4U, "??1last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 4ULL, 4U, "write", 0xE618U, "??0last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::last_error_context", nullptr, 4ULL, 4U, "read", 0xE6C4U, "??1last_error_context@wil@@QEAA@XZ", "likely"},
    {"wil::unique_any_t<class wil::details::unique_storage<struct wil::details::resource_policy<unsigned char *, void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(unsigned char *), struct wistd::integral_constant<uint64_t, 0>, unsigned char *, unsigned char *, 0, std::nullptr_t> > >", nullptr, 0ULL, 8U, "read-write", 0xE52CU, "??0?$unique_any_t@V?$unique_storage@U?$resource_policy@PEAEP6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@ZU?$integral_constant@_K$0A@@wistd@@PEAEPEAE$0A@$$T@details@wil@@@details@wil@@@wil@@QEAA@XZ", "likely"},
    {nullptr, nullptr, 0, 0, nullptr, 0, nullptr, nullptr},
};
inline constexpr std::size_t field_observation_count = (sizeof(field_observations) / sizeof(field_observations[0])) - 1;
inline constexpr BaseLayout bases[] = {
    {nullptr, nullptr, -1, false, nullptr, nullptr},
};
inline constexpr std::size_t base_count = (sizeof(bases) / sizeof(bases[0])) - 1;
inline constexpr VTableLayout vtables[] = {
    {"const CCancelConnection2::`vftable'", 0x15000U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CGetResourceInformation::`vftable'", 0x15028U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CGetConnection3::`vftable'", 0x15050U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CUseConnection::`vftable'", 0x15078U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CGetConnection::`vftable'", 0x150A0U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CGetConnectionPerformance::`vftable'", 0x150C8U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CProviderOpenEnum::`vftable'", 0x150F0U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CGetResourceParent::`vftable'", 0x15138U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {nullptr, 0, 0, nullptr, nullptr},
};
inline constexpr std::size_t vtable_count = (sizeof(vtables) / sizeof(vtables[0])) - 1;
inline constexpr VTableSlotLayout vtable_slots[] = {
    {0x15000U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x15000U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x15000U, 2U, 0x9CC0U, "?GetResult@CCancelConnection2@@MEAAKXZ", "protected: virtual unsigned long __cdecl CCancelConnection2::GetResult(void)", false, 0},
    {0x15000U, 3U, 0xBE00U, "?ValidateRoutedParameters@CCancelConnection2@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CCancelConnection2::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x15000U, 4U, 0xD630U, "?TestProvider@CCancelConnection2@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CCancelConnection2::TestProvider(struct _PROVIDER const *)", false, 0},
    {0x15028U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x15028U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x15028U, 2U, 0xA1D0U, nullptr, nullptr, true, 0},
    {0x15028U, 3U, 0xBF90U, "?ValidateRoutedParameters@CGetResourceInformation@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CGetResourceInformation::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x15028U, 4U, 0xBDD0U, "?TestProvider@CGetResourceInformation@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CGetResourceInformation::TestProvider(struct _PROVIDER const *)", false, 0},
    {0x15050U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x15050U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x15050U, 2U, 0xA1D0U, nullptr, nullptr, true, 0},
    {0x15050U, 3U, 0xB190U, "?ValidateRoutedParameters@CGetConnection3@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CGetConnection3::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x15050U, 4U, 0xBA50U, "?TestProvider@CGetConnection3@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CGetConnection3::TestProvider(struct _PROVIDER const *)", false, 0},
    {0x15078U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x15078U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x15078U, 2U, 0x96D0U, "?GetResult@CUseConnection@@MEAAKXZ", "protected: virtual unsigned long __cdecl CUseConnection::GetResult(void)", false, 0},
    {0x15078U, 3U, 0xD890U, "?ValidateRoutedParameters@CUseConnection@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CUseConnection::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x15078U, 4U, 0xEF50U, "?TestProvider@CUseConnection@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CUseConnection::TestProvider(struct _PROVIDER const *)", false, 0},
    {0x150A0U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x150A0U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x150A0U, 2U, 0xA1D0U, nullptr, nullptr, true, 0},
    {0x150A0U, 3U, 0xB130U, "?ValidateRoutedParameters@CGetConnection@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CGetConnection::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x150A0U, 4U, 0xDCC0U, "?TestProvider@CGetConnection@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CGetConnection::TestProvider(struct _PROVIDER const *)", false, 0},
    {0x150C8U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x150C8U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x150C8U, 2U, 0xA1D0U, nullptr, nullptr, true, 0},
    {0x150C8U, 3U, 0xD450U, "?ValidateRoutedParameters@CGetConnectionPerformance@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CGetConnectionPerformance::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x150C8U, 4U, 0xDD30U, "?TestProvider@CGetConnectionPerformance@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CGetConnectionPerformance::TestProvider(struct _PROVIDER const *)", false, 0},
    {0x150F0U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x150F0U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x150F0U, 2U, 0xA0D0U, "?GetResult@CProviderOpenEnum@@MEAAKXZ", "protected: virtual unsigned long __cdecl CProviderOpenEnum::GetResult(void)", false, 0},
    {0x150F0U, 3U, 0xD670U, "?ValidateRoutedParameters@CProviderOpenEnum@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CProviderOpenEnum::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x150F0U, 4U, 0xD5C0U, "?TestProvider@CProviderOpenEnum@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CProviderOpenEnum::TestProvider(struct _PROVIDER const *)", false, 0},
    {0x15138U, 0U, 0x6300U, nullptr, nullptr, true, 0},
    {0x15138U, 1U, 0x82F0U, nullptr, nullptr, true, 0},
    {0x15138U, 2U, 0xA1D0U, nullptr, nullptr, true, 0},
    {0x15138U, 3U, 0xD760U, "?ValidateRoutedParameters@CGetResourceParent@@MEAAKPEAPEBG00@Z", "protected: virtual unsigned long __cdecl CGetResourceParent::ValidateRoutedParameters(unsigned short const * *, unsigned short const * *, unsigned short const * *)", false, 0},
    {0x15138U, 4U, 0x12C30U, "?TestProvider@CGetResourceParent@@MEAAKPEBU_PROVIDER@@@Z", "protected: virtual unsigned long __cdecl CGetResourceParent::TestProvider(struct _PROVIDER const *)", false, 0},
    {0, 0, 0, nullptr, nullptr, true, 0},
};
inline constexpr std::size_t vtable_slot_count = (sizeof(vtable_slots) / sizeof(vtable_slots[0])) - 1;
}
